### ISSUE TITLE
Server Password cannot have special characters such as ampersand

### ISSUE THREAD

**Issue by RouteTable** [BlueBubblesApp/bluebubbles-server#173] opened 2021-04-01 00:43 UTC
Add either a warning message of which characters not to use, or field validation to throw an error when the server password field loses focus.

**Comment by zlshames** [comment] 2022-08-14 15:27
This is not a bug anymore. Should have closed it way back, but just noticed it now. Just make sure you URL encode it with `%26`

**Closed by zlshames** 2022-08-14 15:27 UTC
