### ISSUE TITLE
Feature request: add an in-app updater

### ISSUE THREAD

**Issue by incIined** [BlueBubblesApp/BlueBubbles-Server#126] opened 2020-12-10 11:37 UTC
What I mean is when there's an update, the program will prompt you to update. Then, the program will download, unpack, and install the new update over the older version automatically. 

The current method of going to the GitHub page, unzipping, drag into applications folder, replacing the older version, double click only to remember macOS makes you hold control or else it won't let you open the file, and then opening the program. Not really ideal, especially if there's frequent updates (and every time I open the program, it prompts me to update lol). 

Thanks!

**Comment by maxwellfortney** [comment] 2020-12-10 17:10
In order for us to implement in-app updating on macOS the released file needs to be [signed](https://www.electron.build/code-signing) with an apple developer account, which costs $100 a year. Which we will be purchasing once we reach that amount in donations.

**Comment by zlshames** [comment] 2020-12-16 16:54
This is a duplicate of this: https://github.com/BlueBubblesApp/BlueBubbles-Server/issues/18

Closing.

**Closed by zlshames** 2020-12-16 16:54 UTC
