### ISSUE TITLE
Option to not run when on battery

### ISSUE THREAD

**Issue by anonymousaga** [BlueBubblesApp/bluebubbles-server#425] opened 2022-10-03 17:27 UTC
When I am on battery, I would rather that BlueBubbles not run. I will not need bluebubbles when on battery because in that case, I will have my mac with me. However, when my mac is at home, plugged in, not sleeping (configured that by turning on internet sharing, which prevents sleep when on AC power), I would like it to run to use bluebubbles. Will such an option be possible? Thanks in advance.

**Comment by zlshames** [comment] 2022-10-05 16:24
This is possible. Here is the API for it. It will likely be released with v1.5.0 (after the v1.4.0 release): https://www.electronjs.org/docs/latest/api/power-monitor

**Comment by anonymousaga** [comment] 2022-10-07 21:01
Thanks. Do you have an idea for the 1.5 release? No pressure to finish it; I'm just wondering.

**Comment by zlshames** [comment] 2022-10-07 21:16
> Thanks. Do you have an idea for the 1.5 release? No pressure to finish it; I'm just wondering.

No, but 1.4.0 should come out shortly. Probably within the next week or so. I'm finishing up the Scheduled Messages API and UI (server). Once that's done, I'm going to release it (maybe a beta first). Then I can start work on 1.5.0 things

**Comment by anonymousaga** [comment] 2022-10-07 21:18
Ok

**Comment by anonymousaga** [comment] 2023-11-07 23:01
Sorry to bother you, but it is 1.9.0 - is the feature there?

**Comment by zlshames** [comment] 2023-11-20 14:49
> Sorry to bother you, but it is 1.9.0 - is the feature there?

Not yet. I guess I forgot about it. Just to be clear, what is the functionality you want? When it detects it's on battery, just close the server? Do you expect it to re-open when back on power?

**Comment by anonymousaga** [comment] 2023-11-20 16:25
Yeah, just have an option for it to close/pause the server when on battery and reopen when connected to AC power. Thanks.

**Comment by zlshames** [comment] 2023-11-20 16:33
> Yeah, just have an option for it to close/pause the server when on battery and reopen when connected to AC power. Thanks.

The problem is, there is no way to detect when the power is connected when the server has already closed itself because the power was disconnected.

**Comment by anonymousaga** [comment] 2023-11-20 17:00
Nevermind, I just realized that ControlPlane (I already use it for other
things) can both quit & reopen BB based on battery. Feel free to close this
issue.

**Closed** 2023-11-20 17:00 UTC
