### ISSUE TITLE
Windows Application, Step 3, Sign in with google, blank window

### ISSUE THREAD

**Issue by smaslamani** [BlueBubblesApp/bluebubbles-server#675] opened 2024-07-18 17:36 UTC
When trying to sign in with google, a pop up appear, with no content, and nothing happens, if I close this pop up the client crashes.

![image](https://github.com/user-attachments/assets/679e3bc2-9f2a-441f-b8af-ca9900cda205)

**Comment by jjoelj** [comment] 2024-07-18 21:26
Look like you opened an issue in the wrong repo, but dupe of https://github.com/BlueBubblesApp/bluebubbles-app/issues/2640

**Closed by jjoelj** 2024-07-18 21:26 UTC
